- name: copy file
  copy: src=linpack.tar.gz dest=/tmp/linpack.tar.gz mode=0777

- name: tar file
  shell: cd /tmp && tar xvf linpack.tar.gz && rm -rf linpack.tar.gz

- name: run install
  shell: "cd /tmp/linpack && ./install.sh"
