- name: tar file
  shell: mkdir -p /tmp/scimarkJava

- name: copy file
  copy: src=scimark2lib.tar.gz dest=/tmp/scimark2lib.tar.gz mode=0777

- name: tar scimark2lib.tar.gz
  shell: "cd /tmp && tar -xvf scimark2lib.tar.gz"