#!/bin/bash

#cpu type
CPU=$(grep 'model name' /proc/cpuinfo |uniq |awk -F : '{print $2}' |sed 's/^[ \t]*//g' |sed 's/ \+/ /g')
echo -e "   CPU model:\t${CPU}\n"

# pyisical cpu number
#Counts=$(grep 'physical id' /proc/cpuinfo |sort |uniq |wc -l)
#echo -e "   Total of physical CPU:\t${Counts}\n"

#
PROCESSOR=$(grep 'processor' /proc/cpuinfo |sort |uniq |wc -l)
echo -e "   Number of CPUs:\t${PROCESSOR}\n"

#cpu utilization
#    a=(`cat /proc/stat | grep -E "cpu\b" | awk -v total=0 '{$1="";for(i=2;i<=NF;i++){total+=$i};used=$2+$3+$4+$7+$8 }END{print total,used}'`)
#    sleep 1
#    b=(`cat /proc/stat | grep -E "cpu\b" | awk -v total=0 '{$1="";for(i=2;i<=NF;i++){total+=$i};used=$2+$3+$4+$7+$8 }END{print total, used}'`)
#    cpu_usage=$(((${b[1]}-${a[1]})*100/(${b[0]}-${a[0]})))
#echo -e "Usage of CPU:\t${cpu_usage}%\n${Line}"

OS=$(uname -s -r -m)
echo -e "   OS Version:\t${OS}%\n"

#Memtotal
Memtotal=$(free -m |grep 'Mem:' |awk -F : '{print $2}' |awk '{print $1}')
echo -e "    Total Memory:\t${Memtotal} MB\n"

#Memo Used
#Memused=$(free -m |grep - |awk -F : '{print $2}' |awk '{print $1}')
#echo -e "   Used Memory:\t${Memused} MB\n"

#Available
#Available=$(free -m |grep - |awk -F : '{print $2}' |awk '{print $2}')
#echo -e "   Available Memory:\t${Available} MB\n"

##number of hard disks
#Disk_num=$(fdisk -l |grep 'Disk' |grep -v 'VolGroup' |awk -F , '{print $1}' | sed 's/Disk identifier.*//g' | sed '/^$/d'|wc -l)
#echo -e "Number Of Disks:\t${Disk_num}\t${Line}"
#
##disks
#Disk=$(fdisk -l |grep 'Disk' |grep -v 'VolGroup' |awk -F , '{print $1}' | sed 's/Disk identifier.*//g' |sed 's/Disk //g' | sed '/^$/d')
#echo -e "Amount Of Disks:\t${Disk}\t${Line}"
#
##patition
#Partion=$(df -hlP |sed -n '2,$p')
#echo -e "Usage Of partions:\n${Partion}\t${Line}"
#
